Update patch set 2
Patch Set 2: Code-Review-1

so even with BR python-docker we end up with old python-docker-py:

# yum install python-docker
Package docker-python is obsoleted by python-docker-py, trying to install python-docker-py-1.10.6-1.el7.noarch instead

BR: python2-docker >= 2.3.0 would get us past this but then we hit missing dep:
Error: Package: python2-docker-2.3.0-1.el7.noarch (delorean-pike-testing)
           Requires: python2-docker-pycreds

which failed to build in virt7-docker http://cbs.centos.org/koji/buildinfo?buildID=17042
I'll try to rebuild it in cloud7-openstack.

Patch-set: 2
Label: Code-Review=-1